name: Force Projets
markdown: redcarpet
markdown_ext: md

url: http://forceprojets.ca

intro: Une expertise de pointe en gestion de projet

navigation:
  - text: ACCUEIL
    url: /index.html
  - text: SERVICES
    url: /services.html
  - text: PROJETS
    url: /projets.html
  - text: MISSION & VALEURS
    url: /mission.html
  - text: À PROPOS
    url: /a-propos.html


domaines:
  - title: Petites et moyennes entreprises
    description: Des services adaptés au contexte de votre entreprise, à votre secteur d'affaires et à vos impératifs de résultats.
    image: turbine.jpg
    link: pme

  - title: Grandes entreprises
    description: Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat.
    image: aluminium.jpg
    link: grandes-entreprises

  - title: Secteur public
    description: Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius.
    image: metro.jpg
    link: publique

