name: Force Projets
markdown: redcarpet
markdown_ext: md

url: http://forceprojets.ca

navigation:
  - text: Services
    url: /index.html
  - text: Mission et Valeurs
    url: /mission.html
  - text: Projets
    url: /projets.html
  - text: A Propos
    url: /a-propos.html
    

