name: Force Projets
markdown: redcarpet
markdown_ext: md

url: http://forceprojets.ca

intro: Une expertise de pointe en gestion de projet

navigation:
  - text: ACCUEIL
    url: /index.html
  - text: SERVICES
    url: /services.html
  - text: PROJETS
    url: /projets.html
  - text: MISSION & VALEURS
    url: /mission.html
  - text: À PROPOS
    url: /a-propos.html


domaines:
  - title: Petites et moyennes entreprises
    description: Des services adaptés au contexte de votre entreprise, à votre secteur d'affaires et à vos impératifs de résultats.
    image: turbine.jpg
    link: pma

  - title: Grandes entreprises
    description: L'expérience des meilleures pratiques en gestion de projet au sein de différentes structures d'entreprise.
    image: aluminium.jpg
    link: grandes-entreprises

  - title: Secteur public
    description: L'expertise des processus et la connaissance des exigences de gouvernance des projets publics.
    image: metro.jpg
    link: public

